### ISSUE TITLE
Connecting via ssh key fails with password blank

### ISSUE THREAD

**Issue by ksotin** [ColdGrub1384/Pisth#15] opened 2019-05-14 12:05 UTC
I cannot seem to pass the authentication via keys when I leave the password blank. The keys are correct, which was tested on another client.

**Comment by ColdGrub1384** [comment] 2019-05-14 12:13
Do the private key have a passphrase? If yes, you should put the SSH passphrase in password field.

**Comment by ksotin** [comment] 2019-05-14 16:06
@ColdGrub1384 No, no passphrase.

**Comment by ColdGrub1384** [comment] 2019-05-16 00:54
How did you generated the SSH keys? So I can try to reproduce the issue.

**Comment by ColdGrub1384** [comment] 2019-05-16 00:55
As the keys work on other SSH clients, that may be an issue of [`libssh2`](https://www.libssh2.org).

**Comment by ksotin** [comment] 2019-05-16 10:50
@ColdGrub1384 I generated the keys using ssh-keygen command on my Mac.

**Comment by ColdGrub1384** [comment] 2019-05-19 14:58
Ok. I think I finally found the issue. I have to update `libssh2` to a version that supports new OpenSSH keys format. https://github.com/libssh2/libssh2/issues/68

**Comment by ksotin** [comment] 2019-05-19 15:20
Thanks for your effort!

**Comment by ColdGrub1384** [comment] 2019-05-19 17:33
I just fixed it! The problem was that macOS was generating SSH keys in a "new" format unsupported by the library I was using, but I just had to update it. I will release an update today.

**Comment by ColdGrub1384** [comment] 2019-05-22 12:33
The issue is now fixed on the App Store version. Thank you for reporting.

**Closed by ColdGrub1384** 2019-05-22 12:33 UTC
Labels: bug
